#python program to take the name , age , occupation from user 
print("enter your name")
name=input()
print(name)
print("enter your age ")
age=int(input())
print(age)
print("enter your occupation ")
occupation=input()
print(occupation)
print("enter your favorite food")
food=input()
print(food)